import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/navbar';
// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen flex-col">
          <header>
            <Navbar />
          </header>
          <main className="flex-grow w-full max-w-[1200px] px-12 py-4 mx-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
